using Content.Client.UserInterface.Controls;
using Content.Shared._RMC14.Power;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Power;

[GenerateTypedNameReferences]
public sealed partial class RMCPortableGeneratorWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    private EntityUid _entity;

    public float? MaximumPower;

    public event Action<int>? OnPower;
    public event Action<bool>? OnState;
    public event Action? OnEjectFuel;

    public RMCPortableGeneratorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TargetPower.IsValid += IsValid;
        TargetPower.ValueChanged += (args) =>
        {
            OnPower?.Invoke(args.Value);
        };

        StartButton.OnPressed += _ => OnState?.Invoke(true);
        StopButton.OnPressed += _ => OnState?.Invoke(false);
        FuelEject.OnPressed += _ => OnEjectFuel?.Invoke();
    }

    public void SetEntity(EntityUid entity)
    {
        _entity = entity;
        EntityView.SetEntity(entity);
    }

    private bool IsValid(int arg)
    {
        if (arg < 0)
            return false;

        if (arg > (MaximumPower / 1000.0f ?? 0))
            return false;

        return true;
    }

    public void Update(RMCPortableGeneratorUiState state)
    {
        MaximumPower = state.MaximumPower;

        if (!TargetPower.LineEditControl.HasKeyboardFocus())
            TargetPower.OverrideValue((int)(state.TargetPower / 1000.0f));

        var unanchored = !_entityManager.GetComponent<TransformComponent>(_entity).Anchored;
        var on = !unanchored && state.On;
        var off = !unanchored && !state.On;

        LabelUnanchored.Visible = unanchored;
        StopButton.Visible = on;
        StartButton.Visible = off;

        if (on)
        {
            StatusLabel.Text = _loc.GetString("portable-generator-ui-status-running");
            StatusLabel.SetOnlyStyleClass("Good");
        }
        else
        {
            StatusLabel.Text = _loc.GetString("portable-generator-ui-status-stopped");
            StatusLabel.SetOnlyStyleClass("Danger");
        }

        FuelLeftTitle.Text = _loc.GetString("rmc-portable-generator-ui-fuel-left-title", ("type", state.FuelType));
        FuelFraction.Value = state.RemainingFuel - (int) state.RemainingFuel;
        FuelLeft.Text = ((int) Math.Floor(state.RemainingFuel)).ToString();
    }
}
