- type: job
  parent: RMCSurvivorCLFBase
  id: RMCSurvivorCLFEngineer
  name: cm-job-name-clf-engineer
  icon: RMCJobIconCLFEngineer
  startingGear: RMCGearSurvivorCLFEngineer
  spawnMenuRoleName: CLF Engineer (Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - CLF
    - type: Skills
      skills:
        RMCSkillFireman: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 2
        RMCSkillMedical: 1
        RMCSkillPowerLoader: 1
        RMCSkillVehicles: 1
        RMCSkillEndurance: 1
        RMCSkillJtac: 1
    - type: JobPrefix
      prefix: cm-job-prefix-clf-engineer
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetCLF
  hidden: true

- type: startingGear
  id: RMCGearSurvivorCLFEngineer
  equipment:
    head: RMCHelmetWelding
    mask: RMCM5Bayonet # TODO RMC14
    ears: RMCHeadsetDistressCLF
  #  eyes: RMCMesonGoggles TODO RMC14
    jumpsuit: RMCJumpsuitCLFWebbing
    outerClothing: RMCCoatMilitia
    gloves: CMHandsInsulated
    id: RMCIDCardCLFEngineer
    belt: CMBeltUtilityFilled
    back: RMCSatchelLightpackWelder
    pocket1: RMCPouchSurvivalFill
    pocket2: RMCPouchFirstAidInjectors
  storage:
    back:
    - RMCExplosiveBreachingCharge
    - RMCExplosiveBreachingCharge
    - RMCExplosiveBreachingCharge
    - CMSheetMetal50
    - CMSheetPlasteel30
    - RMCExplosivePlastic
    - RMCGrenadeMolotov
    - CMMRE
    - RMCFlashlight

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSurvivorCLFEngineer
  name: clf engineer spawn point
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorCLFEngineer
  - type: Sprite
    state: clf_spawn
