- type: job
  parent: RMCSurvivorCLFBase
  id: RMCSurvivorCLFSoldier
  name: cm-job-name-clf-soldier
  icon: RMCJobIconCLFSoldier
  spawnMenuRoleName: CLF Soldier (Survivor)
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - CLF
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillMeleeWeapons: 1
        RMCSkillPolice: 2
        RMCSkillFireman: 1
        RMCSkillConstruction: 1
        RMCSkillEngineer: 1
        RMCSkillMedical: 1
        RMCSkillVehicles: 1
        RMCSkillEndurance: 1
        RMCSkillJtac: 1
    - type: JobPrefix
      prefix: cm-job-prefix-clf-soldier
    - type: EquipSurvivorPreset
      preset: RMCSurvivorPresetCLF
  hidden: true

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSurvivorCLFSoldier
  name: clf soldier spawn point
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorCLFSoldier
  - type: Sprite
    state: clf_spawn
